# aggregate data from 2 samplers running on different nodes
# CN1:
prdcr_add name=prdcr1 host=piccinal-ldms-test port=10001 xprt=sock type=active interval=20000000
prdcr_start name=prdcr1
# CN2:
prdcr_add name=prdcr2 host=piccinal-ldms-test2 port=10001 xprt=sock type=active interval=20000000
prdcr_start name=prdcr2
# configure aggregator to update all schemas (i.e. meminfo and vmstat)
updtr_add name=updtr1 interval=1000000 auto_interval=true
updtr_prdcr_add name=updtr1 regex=.*
updtr_start name=updtr1
