# aggregate data from 2 samplers running on different nodes
# CN1:
prdcr_add name=prdcr1 host=piccinal-ldms-test port=10001 xprt=sock type=active interval=20000000
prdcr_start name=prdcr1
# CN2:
prdcr_add name=prdcr2 host=piccinal-ldms-test2 port=10001 xprt=sock type=active interval=20000000
prdcr_start name=prdcr2
