# load, config and start kafka storage
load name=store_kafka
config name=store_kafka path=/shared/cscs/etc/kafka.conf

strgp_add name=kafka_store plugin=store_kafka container=148.187.83.175:9092 decomposition=/shared/cscs/etc/decomp.json schema=meminfo
strgp_prdcr_add name=kafka_store regex=.*
# If you later want to store multiple schemas (not just meminfo), switch to
# regex=.* (or regex=mem.*) and re-add decomposition=/home/almalinux/etc/ldms/decomp.json

strgp_start name=kafka_store
# status # -> kafka_store/metrics
